### ISSUE TITLE
Any way to bring this to app as well?

### ISSUE THREAD

**Issue by reggi** [alex-whitney/express-promise-router#13]
I just ran into a bug I was using a promsied router for app and I don't wanna manage two different kinds of callbacks. How can I get app working just like a route?

```
var router = require("express-promise-router")()
app.get = router.get
app.post = router.post
app.use = router.use
```

Would something like this do the trick?

**Comment by alex-whitney** [comment]
No, I don't imagine that would work as you expect. `express-promise-router` creates an Express router internally, which is what each of the verbs invoke.

Is there any reason why you would not be able to use an Express router? As far as I'm aware, you should be able to swap a router in place of `app` in your route definitions, then just mount the router to your app using `app.use(router)`.

**Comment by reggi** [comment]
Yeah that's what I went' ahead and did. Not a problem, can close. Thanks!
