### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by joepie91** [alex-whitney/express-promise-router#19]
Per [semantic versioning](https://gist.github.com/joepie91/9b9dbd8c9ac3b55a65b2#semantic-versioning), a module should be released as 1.0.0 once the API is considered "production-stable", and follow semantic versioning rules from that point on.

Given that `express-promise-router` seems rather stable and 'complete' to me, is a 1.0.0 release planned any time soon?

**Comment by alex-whitney** [comment]
Just published 1.0.0!

**Comment by billinghamj** [comment]
Just to clarify - are there any breaking changes from 0.0.9 to 1.0.0?

**Comment by alex-whitney** [comment]
No
