### ISSUE TITLE
Remove dependency on bluebird

### ISSUE THREAD

**Issue by danthegoodman** [alex-whitney/express-promise-router#28]
I'd like to have the dependency on bluebird removed.

Since the two latest LTS versions of Node ship with Promises, I think it's acceptable to not need a promise library. Another alternative is to use `any-promise` to allow others to bring their own promise implementation. I'd be happy to make a PR for this, either way you want to go.

**Comment by mormahr** [comment]
I started working on this a while ago, but stopped. I'm totally in favor of this. I'd suggest going without a library and dropping support for Node < 4. On a related note: I'm currently working to remove the lodash dependency. ☺️

**Comment by mormahr** [comment]
I restarted working on this. I plan to improve the testing code with respect to promise handling at the same time (ongoing effort). You can follow progress at my [no_bluebird](https://github.com/mormahr/express-promise-router/tree/no_bluebird) branch. 

As far as i can tell we'd need to drop support for node 0.10. According to the Unit Tests 0.12 would still work.

![ci version overview](https://cloud.githubusercontent.com/assets/7482056/22635695/a932cc84-ec35-11e6-8e8f-9cbfa49ca766.png)

**Comment by mormahr** [comment]
I merged this to master and will tag a new major / breaking release relatively soon!

**Comment by danthegoodman** [comment]
@mormahr Thanks!

**Comment by mormahr** [comment]
@danthegoodman Oh well it always takes longer than you expect. I just released v2.0.0-alpha.1 (alpha because i'm paranoid) but we will be using it in production anyway (🙄) starting next week. ☺️
So stable release in a week or so, i don't see any problems as long as everyone is using at least node 4 (which they should be anyway).
