### ISSUE TITLE
No support for .param

### ISSUE THREAD

**Issue by joepie91** [alex-whitney/express-promise-router#5]
When using `router.param` to define parameter pre-processing callbacks, returned failing promises from the pre-processing callback are not correctly handled - they result in the error being dumped to stdout and the pageload indefinitely hanging. The behaviour here should probably be the same as for request handling middleware.

**Comment by alex-whitney** [comment]
I agree! Thanks for pointing this out - this is fixed in #6

**Comment by joepie91** [comment]
Awesome, thanks :)
